# Numpy
* Numerical Python을 의미하는 넘파이는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지 입니다.   
* 루프를 사용하지 않고 대량의 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보장합니다.       
* Numpy는 C/C++ 과 같은 저수준 언어 기반의 호환 API를 제공합니다.   
* 구글의 대표적인 딥러닝 프레임워크인 텐서플로는 이러한 방식으로 배열 연산 수행 속도를 개선하고 넘파이와도 호환될 수 있게 작성됐습니다.

In [1]:
import numpy as np # numpy 모듈 임포트

In [6]:
array1= np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array shape', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 shape', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array shape (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 shape (1, 3)


* np.array: ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환   
* np.shape: ndarray의 차원과 크기를 튜플 형태로 나타냄

## ndarray의 타입
1. 숫자형: int(8bit, 16bit, 32bit)   
2. unsigned int형: unsigned int(8bit, 16bit, 32bit)   
3. float형: float(16bit, 32bit, 64bit, 128bit)
4. complex형: 위보다 더 큰 숫자 값이나 정밀도를 위해 제공   
   
ndarray내의 데이터 타입은 ``` dtype ```속성으로 확인할 수 있습니다.

In [8]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3= np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


이처럼 ndarray는 데이터 값이 모두 같은 데이터 타입이어야 하므로 서로 다른 데이터 타입이 섞여 있을 경우 데이터 타입이 더 큰 타입으로 변환되어 int형이 유니코드 문자로, int형이 float형으로 변환됐습니다.   
   
   ndarray 내 데이터 값의 타입 변경도 ``` astype ```메서드를 이용해 할 수 있습니다.

## ndarray를 편리하게 생성하기 - arange, zeros, ones
특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우 ``` arange(), zeros(), ones() ```를 이용해 쉽게 ndarray를 생성할 수 있습니다. 

In [10]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

ones_array = np.ones((3,2))
print(ones_array)
print(ones_array.dtype, ones_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape()
``` reshape() ```메서드는 ndarray를 특정 차원 및 크기로 변환합니다. 변환을 원하는 크기를 함수 인자로 부여하면 됩니다.

In [11]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


```reshape() ```는 지정된 사이즈로 변경이 불가능하면 오류를 발생합니다.

## 넘파이의 ndarray의 데이터 세트 선택하기 - indexing
1. 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됩니다.
2. 슬라이싱: 슬라이싱은 연속된 인덱스 상의 ndarray를 추출하는 방식입니다. ':'사이에 시작 인덱스와 종료 인덱스를 표시하면, 시작인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환합니다.
3. 팬시 인덱싱: 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환합니다.
4. 불린 인덱싱: 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환합니다.

### 단일 값 추출

In [13]:
# 1부터 9까지 1차원 ndarray 생성
array1 = np.arange(start = 1, stop = 10)
print('array1:',array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value', value)
print(type(value))

print('맨 뒤의 값:', array1[-1])

array1: [1 2 3 4 5 6 7 8 9]
value 3
<class 'numpy.int32'>
맨 뒤의 값: 9


### 슬라이싱

In [14]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

# 1. ':'기호 앞에 시작 인덱스를 생략하면 자동으로 맨 앞 인덱스인 0으로 간주
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

# 2. ':'기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 뒤의 인덱스로 간주
array5 = array1[3:]
print(array5)

# 3. ':'기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주합니다.
array6 = array1[:]
print(array6)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [15]:
# 2차원 ndarray에서 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2] \n',array2d[0:2,0:2])
print('array2d[1:3,0:3] \n',array2d[1:3,0:3])
print('array2d[1:3,:] \n',array2d[1:3,:])
print('array2d[:,:] \n',array2d[:,:])
print('array2d[:2,1:] \n',array2d[:2,1:])
print('array2d[:2,0] \n',array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


### 팬시 인덱싱
팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식입니다.

In [17]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>',array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱
불린 인덱싱은 조건 필터링과 검색을 동시에 할 수 있기 때문에 자주 사용되는 인덱싱 방식입니다.

In [19]:
array1d = np.arange(start=1,stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 인덱싱 결과 >>', array3)

# 조건식이 있는 ndarray
print('조건식 결과')
print(array1d > 5)

array1d > 5 인덱싱 결과 >> [6 7 8 9]
조건식 결과
[False False False False False  True  True  True  True]


1. array1d > 5와 같이 ndarray의 필터링 조건을 [] 안에 기재
2. False값은 무시, True 값에 해당하는 인덱스 값만 저장
3. 저장된 인덱스 데이터 세트로 ndarray 조회

## 행렬의 정렬 - sort(), argsort()

### 행렬 정렬
1. np.sort() : 원 행렬은 유지한 채 원 행렬이 정렬된 행렬을 반환
2. ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며, 반환 값은 None

In [21]:
org_array = np.array([3,1,9,5])
print('원본 행렬',org_array)

#np.sort로 정렬
sort_array1 = np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort()호출 후 원본 행렬',org_array)

#ndarray.sort로 정렬
sort_array2 = org_array.sort()
print('org_array.sort()호출 후 반환된 행렬',sort_array2)
print('org_array.sort()호출 후 원본 행렬',org_array)

# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 정렬:',sort_array1_desc)

원본 행렬 [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort()호출 후 원본 행렬 [3 1 9 5]
org_array.sort()호출 후 반환된 행렬 None
org_array.sort()호출 후 원본 행렬 [1 3 5 9]
내림차순 정렬: [9 5 3 1]


In [22]:
# 2차원 배열 정렬
array2d = np.array([[8,12],
                   [7,1]])
sort_array2d_axis0 = np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

In [24]:
org_array = np.array([3,1,9,6,4])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 4 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 4 0 1]


In [25]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스',sort_indices_asc)
print('성적 오름차순으로 정렬 시 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 [0 2 4 1 3]
성적 오름차순으로 정렬 시 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적 (행렬 곱)
두 행렬 A와 B의 내적은 ```np.dot() ```을 이용해 계산이 가능합니다.   
A와 B의 내적은 왼쪽 행렬의 row(행)와 오른쪽 행렬의 column(열)의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값입니다.

In [26]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print('행렬의 내적 결과:\n',dot_product)

행렬의 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치행렬
원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬이라고 합니다. ```np.transpose() ```를 이용하여 구할 수 있습니다.

In [27]:
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
